[project]
name = "finalproject-ozhiganov-m26-555"
version = "0.1.0"
description = "ValutaTrade Hub - console application for tracking and simulating currency trading"
readme = "README.md"
authors = [
    { name = "Vlad Ozhiganov", email = "slava.northern@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "prettytable>=3.18.0",
    "python-dotenv>=1.2.4",
    "requests>=2.34.2",
]

[project.scripts]
valutatrade = "valutatrade_hub.cli.interface:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "valutatrade_hub"
module-root = ""

[dependency-groups]
dev = [
    "ruff>=0.16.10",
]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.valutatrade]
rates_ttl_seconds = 300
default_base_currency = "USD"
log_level = "INFO"
log_format = "%(levelname)s %(asctime)s %(message)s"